version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/jsb_medjez_amar
      - JWT_SECRET=your_jwt_secret_key_here
      - NODE_ENV=production
    volumes:
      - ./uploads:/app/uploads

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
